- src/viur_cli/conf.py
- src/viur_cli/utils.py
- Allows to run `viur` command from anywhere inside the project folder by resolving and chdir'ing backwards
- Improved error reporting and output (fatal error stops program execution)
> Improving conf module

- src/viur_cli/cli.py
This fix load the config only when the command are not create or init.
> Fix for Init and Create

- src/viur_cli/deploy.py
This automatically sorts the indexes from index.yaml by kind name, making it easier to follow and diff against.
Fixes #2.
> Sort index.yaml when deployed

- src/viur_cli/scripts/viur_2to3.py
https://github.com/viur-framework/viur-core/pull/562
https://github.com/viur-framework/viur-core/pull/513
> Improvements for viur_2to3 on PR #562 and #513

- README.md
Added info about how to run the viur-2to3 script
> Update README.md about viur-2to3

- src/viur_cli/scriptor/cli.py
detects if session is invalid and asks user to reconfigure in that case. also corrected spelling mistake when overwriting changed files
> Improving and fixing script command

- src/viur_cli/local.py
- Consequent use of `utils.system()`
- Use `os.path.join` to make configuration less error-prone
- Refactored `do_checks()`
> fix: Improve `local` module

- src/viur_cli/build.py
- src/viur_cli/utils.py
Also removed unused imports from `build.py`.
> feat: Provide secure and error-prone `utils.rmdir`

- src/viur_cli/install.py
Furthermore refactoring the entire code, remove duplicates and use modern `Pathlib`.
> feat: Add targets to all install softwares and ensure a specific version is correctly working

- src/viur_cli/scripts/viur_2to3.py
https://github.com/viur-framework/viur-core/pull/800
> feat: Add replacements from refactoring in viur-core/#800

- src/viur_cli/conf.py
- src/viur_cli/setup.py
I deleted the obsolete "viur init" command. We already have a project.json in the viur-base project.
This PR is linked to #57 .
> deleted 'viur init' command

- src/viur_cli/scripts/viur_2to3.py
> added sameSite to viur_2to3 script

- src/viur_cli/build.py
- src/viur_cli/cli.py
- src/viur_cli/conf.py
- src/viur_cli/deploy.py
- src/viur_cli/install.py
- src/viur_cli/local.py
- src/viur_cli/setup.py
- src/viur_cli/tool.py
- src/viur_cli/update.py
I added some partly generated documentation to the viur cli and fixed -h to **allways** work.
It also shows up, when you use the --help command.
> Add documentation

- CHANGELOG.md
- CONTRIBUTING.md
- src/viur_cli/version.py
> added changelog and version number

- src/viur_cli/build.py
- src/viur_cli/conf.py
Hello @Grashalmbeisser,
here are two fixes for v2.0.0rc3 :smile:
> Fixes for v2.0

- CHANGELOG.md
- src/viur_cli/local.py
Bugfixes in deployment
get user info
> added default gcloud accounnt print for env

- src/viur_cli/conf.py
The migrate function now adds the application name in the default profile and deletes the obsolete entry
> added project json key rewriting and addition

- src/viur_cli/local.py
Hard Enforcement of Gcloud tool usage
> enforcing gcloud tool usage and LogIn

- src/viur_cli/cloud.py
- src/viur_cli/local.py
Upodated Some hints and Documentation
> Added hints to several viur-cli commands

- src/viur_cli/conf.py
> fix: Read `project.json` into `conf` singleton only when needed

- src/viur_cli/package.py
- src/viur_cli/setup.py
version <3.13 support
package.py version logging errors
> added smaller bugfixes 

- src/viur_cli/utils.py
> feat: Add `$(ref)`-variable for version string
